### ISSUE TITLE
Update used python version

### ISSUE THREAD

**Issue by alecello** [WEEE-Open/pxenow#8]
SCHIFOMACCHINA got recently updated and now `python3.7` as a command is not available anymore, we should switch to `python3.8`

**Comment by lvps** [comment]
TODO: use python3, no need for a more specific version

Il gio 15 ott 2020, 09:51 Alessandro Celoria <notifications@github.com> ha
scritto:

**Comment by lvps** [comment]
Also it's already done: `#!/usr/bin/env python3`
